baseURL = "http://localhost/"
title = "Articles by Sudip Ghimire"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2021-{year} Sudip ghimire. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true



# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

[blackfriday]
  hrefTargetBlank = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

