# mainSections = ["post", "posts"] # Default to ["posts"].
description = "I am Sudip Ghimire, a programmer from Nepal. Here I write my ideas on technical as well as non-technical side of mine"

menusPosition = "right" # Menus position: right(default), left or center.

palette = "teal" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.
# palettes = [] # Disable palette switcher.

fixedHeader = false # Turn on/off fixed header.

# Google Adsense
# googleAdsense = ""

math = true # Enable math globally.
toc = true # Disable TOC globally.
# breadcrumb = false # Disable breadcrumb
tocWordCount = 1 # enable/disable in front matter
# main sections
mainSection = ["posts"]
# string to seperate title in slug
titleSeperator = "-"
# weather to enable comment
comment = true
# Date Format
dateFormat = "Jan 2, 2006"
# Whether to show powered by.
poweredBy = false 
# logo image
logo = "/images/logo.webp"
# brand name
brand = "Sudip"
# site theme
color = "dynamic"
# weather to enable full width
fullWidth = false

featuredPostCount = 10 # The number of featured posts shown in sidebar.
recentPostCount = 5 # The number of recent posts shown in sidebar.
relatedPostCount = false # The number of related posts.
categoryCount = 100 # The number of categories shown in sidebar.
tagCount = 100 # The number of tags shown in sidebar.
seriesCount = 100 # The number of series shown in sidebar.

# Custom CSS and JS
customCSS = []
customJS = []

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

#[analytics]
  # baidu = "" # Baidu Analytics

# Site verification
[siteVerification]
  google = ""
  bing = ""
  baidu = ""
  baiduUnion = "" # Baidu Union
  so = ""
  sogou = ""
  shenma = ""

# [creativeCommons]
  # by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.

[utterances]
  repo = "sudipghimire533/comments"
  # issueTerm = "url" # pathname, url, title, og:title
  label = "comment"
  theme = "preferred-color-scheme" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

#[reward]
  #alipay = "images/reward/alipay.png"
  #wechat = "images/reward/wechat.png"

# [share]
 # addThis = "ra-60bbe41920ca73e6" # AddThis pubid.

[fontSize] # Comment or remove this settings to disable font size switcher.
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.rem"
