email = "sudipghimire533@gmail.com"
facebook = "sudip.ghimire.533"
github = "sudipghimire533"
gitlab = "sudipghimire533"
# linkedin = "yourlinkedinusername"
stackoverflow = "10084485"
twitter = "sudipghimire533"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
telegram = "sudipghimire533"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
medium = "sudipghimire533" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
